Add image generate list get features
aibtcdev/aibtcdev-services pull request #17
Opened 2024-12-13 15:54 UTC by r0zar

This pull request introduces a new image generation feature using OpenAI's API, along with some code clean-up and minor improvements. The most important changes include adding the `openai` package, updating service endpoints, and integrating the new `ImageGeneratorDO` Durable Object.

### New Feature: Image Generation

* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L21-R22): Added the `openai` package to dependencies.
* [`src/config.ts`](diffhunk://#diff-c3095d5010e65c52737a98a5d618ea24049ebe90c8470752426081d70ed6e012L37-R37): Added `/image` to the list of supported API service endpoints.
* [`src/durable-objects/image-do.ts`](diffhunk://#diff-9e7110ec1d3798802c4564bdc9e7e7d5923b24dbd3a649e57bf5a2d52be8560dL20-R20): Implemented the `ImageGeneratorDO` Durable Object for generating images using OpenAI's API. This includes initializing the OpenAI client, handling requests, generating images, and storing them. [[1]](diffhunk://#diff-9e7110ec1d3798802c4564bdc9e7e7d5923b24dbd3a649e57bf5a2d52be8560dL20-R20) [[2]](diffhunk://#diff-9e7110ec1d3798802c4564bdc9e7e7d5923b24dbd3a649e57bf5a2d52be8560dL29-R29) [[3]](diffhunk://#diff-9e7110ec1d3798802c4564bdc9e7e7d5923b24dbd3a649e57bf5a2d52be8560dL49-R67) [[4]](diffhunk://#diff-9e7110ec1d3798802c4564bdc9e7e7d5923b24dbd3a649e57bf5a2d52be8560dL79-R80) [[5]](diffhunk://#diff-9e7110ec1d3798802c4564bdc9e7e7d5923b24dbd3a649e57bf5a2d52be8560dL93-R103) [[6]](diffhunk://#diff-9e7110ec1d3798802c4564bdc9e7e7d5923b24dbd3a649e57bf5a2d52be8560dL140-R143) [[7]](diffhunk://#diff-9e7110ec1d3798802c4564bdc9e7e7d5923b24dbd3a649e57bf5a2d52be8560dL150-R153)
* [`src/durable-objects/index.ts`](diffhunk://#diff-2fc439b86e4cf65f4c2ab7b39b2661f5f912de076af832d8991fa0cf61980699R7): Exported the new `ImageGeneratorDO`.
* [`src/index.ts`](diffhunk://#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L4-R7): Integrated the `ImageGeneratorDO` into the main application, including routing requests to the new Durable Object. [[1]](diffhunk://#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L4-R7) [[2]](diffhunk://#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R75-R80)
* [`wrangler.toml`](diffhunk://#diff-b1b9719b6eae4103d520f1e902420f5073b5e18a5a47aa73feed71a037557c98R44-R47): Added configuration for the `ImageGeneratorDO` Durable Object.

### Code Clean-Up

* [`src/durable-objects/image-do.ts`](diffhunk://#diff-9e7110ec1d3798802c4564bdc9e7e7d5923b24dbd3a649e57bf5a2d52be8560dL79-R80): Removed unused metadata and simplified error responses. [[1]](diffhunk://#diff-9e7110ec1d3798802c4564bdc9e7e7d5923b24dbd3a649e57bf5a2d52be8560dL79-R80) [[2]](diffhunk://#diff-9e7110ec1d3798802c4564bdc9e7e7d5923b24dbd3a649e57bf5a2d52be8560dL140-R143) [[3]](diffhunk://#diff-9e7110ec1d3798802c4564bdc9e7e7d5923b24dbd3a649e57bf5a2d52be8560dL150-R153)

2024-12-13 21:34 UTC, whoabuddy requested changes
Two small things but otherwise looks great! The formatting looks super wide in the PR but after pulling it locally seems fine.

2024-12-13 21:34 UTC, whoabuddy commented on worker-configuration.d.ts
> +	OPENAI_API_KEY: process.env.OPENAI_API_KEY;
This value should be string, you can use it through the worker env that's part of the request.

```suggestion
	OPENAI_API_KEY: string;
```

2024-12-13 21:34 UTC, whoabuddy commented on wrangler.toml
>  [[migrations]]
Also needs a migration, each time new durable objects get added a new block has to be added here. Can go below v2.

```
[[migrations]]
tag = "v3"
new_classes = ["ImageGeneratorDO", "TokenMetadataDO"]
```

2024-12-15 18:32 UTC, whoabuddy commented on src/utils/auth-helper.ts
I know there's a note in the PR for this but it's still been bugging me since I first reviewed it.

For future reference changes like this should be kept locally not committed as part of the PR.

2024-12-17 06:10 UTC, whoabuddy commented
@r0zar bumping the small changes needed here

2024-12-18 09:33 UTC, r0zar reviewed
LGTM now

2024-12-19 19:44 UTC, human058382928 approved these changes

2024-12-19 21:36 UTC, whoabuddy approved these changes
LGTM - thank you!

2024-12-19 21:36 UTC, merged